# Generated by Django 4.2.7 on 2023-11-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("principal", "0002_product_fixed_command_cost_product_holding_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="fixed_command_cost",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="holding_rate",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="service_level",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_cost",
            field=models.FloatField(default=0.0),
        ),
    ]
